export const advancedHooks = [
  {
    title: 'useReducer',
    to: 'useReducer',
    description: null,
    usage: null,
    stackBlitz: null,
  },
  {
    title: 'useCallback',
    to: 'useCallback',
    description: null,
    usage: null,
    stackBlitz: null,
  },
  {
    title: 'useMemo',
    to: 'useMemo',
    description: null,
    usage: null,
    stackBlitz: null,
  },
  {
    title: 'useRef',
    to: 'useRef',
    description: null,
    usage: null,
    stackBlitz: null,
  },
  {
    title: 'useImperativeHandle',
    to: 'useImperativeHandle',
    description: null,
    usage: null,
    stackBlitz: null,
  },
  {
    title: 'useLayoutEffect',
    to: 'useLayoutEffect',
    description: null,
    usage: null,
    stackBlitz: null,
  },
  {
    title: 'useDebugValue',
    to: 'useDebugValue',
    description: null,
    usage: null,
    stackBlitz: null,
  },
];
